### ISSUE TITLE
Simple FullStorageManager tagger

### ISSUE THREAD

**Issue by Loonride** [sjyk/deeplens-cv#12]
The current examples create a FullStorageManager by doing something like this:

```
manager = FullStorageManager(CustomTagger(FixedCameraBGFGSegmenter().segment, batch_size=100), CropSplitter(), 'videos')
```

If I don't want the bounding box to be changed at all, what is the simplest way to pass in options that accomplishes this? It seems that using `FixedCameraBGFGSegmenter().segment` creates a foreground bounding box which cuts off portions of the frames slightly.

**Comment by swjz** [comment]
Yes - in FullStorageManager our assumption is that you want to access the foreground (or specific objects) much more frequently than the background (which contains nothing you need in most cases). If you really, really wanted to have a "simple" tagger, you may define a function like this to force the entire thing to be foreground:

```python
def basic_tagger(height, width):
    return {'label': 'foreground', 'bb': Box(0, 0, width, height)}
```

**Comment by j2zhao** [comment]
I've actually just pushed a commit that might work a bit better! You can try running the put_fix() command on FullStorageManager with an empty list of crops. It hasn't actually been tested on an empty list yet, but it should return an uncropped video.

**Comment by swjz** [comment]
Closed due to inactivity - feel free to reopen it if you have further questions!
